### ISSUE TITLE
CoffeeScript problem

### ISSUE THREAD

**Issue by stephane-r** [philippotto/Sublime-EvalPrinter#2] opened 2014-09-03 11:47 UTC
I have a problem when I want to use the plugin on coffeescript. Indeed, the code does not appear in the console, I get this error message :

http://img4.hostingpics.net/pics/182935screenshotsublimetext.jpg

Can you help me ?

**Comment by philippotto** [comment] 2014-09-03 12:03
On the first glance, I would have said that EvalPrinter thinks that your code is JavaScript and not CoffeeScript. The language is determined by using the syntax which is set for the file.
But since your code highlighting looks correct, this is probably not the reason.

On the second glance, I noticed a mismatch between the selected code (`if $.cookie ...`) and the error message (`result = [0, 1, 2, 3, 4, ...].map ...`). Do you know where the code from the error message originates? Did you evaluate that in another view?

Can you look at the console output of Sublime? Via `View -> Show console`. Maybe we can get a hint, what went wrong.

Does evaluation of JavaScript work without any problems?

**Comment by stephane-r** [comment] 2014-09-03 12:34
Hi,
Thank you for your quick response :)

The code was during a test on a new file. If I CTRL + SHIT + ALT + ENTER, nothing happens in my current file. But if I do it in a blank file, the console opens.

Here's a new screenshot : http://img4.hostingpics.net/pics/907222screenshotsublimetext.jpg

Thank you so much!

**Comment by philippotto** [comment] 2014-09-03 12:55
Ok, the screenshot shows some errors of EvalPrinter, but I assume that they are only the result of another error. Can you scroll a little bit up (or make the console window bigger)? By the way, you can upload the screenshot directly via Github by dragging the picture in the comment box ;)

I guess that something goes wrong when opening the subprocess for `coffee`. Noticeable is that the Better CoffeeScript package also fails when doing the call to subprocess.
Is the coffee compiler in your PATH? Respectively, can you invoke "coffee" from a normal command line?

**Comment by stephane-r** [comment] 2014-09-03 13:07
Thank for the picture in comment box ;)

Screenshot with full height :

![screenshot-sublime-text](https://cloud.githubusercontent.com/assets/4712791/4134316/0ecdce26-336b-11e4-9bb6-445ae0600d2f.jpg)

About coffee, yep : 

![coffee](https://cloud.githubusercontent.com/assets/4712791/4134310/ff359c64-336a-11e4-9435-510930353e13.jpg)

**Comment by philippotto** [comment] 2014-09-03 13:55
Thank you! Unfortunately, the error message isn't really helpful. I updated the package to improve the error messaging.
You should be able to update the EvalPrinter package to version 1.1.2. Maybe you have to wait an hour because package control polls the releases from Github.
Alternatively, you could check out the repository and put in the Sublime Text package directory.

After having updated the package, I hope that the console will yield a better error message. Sorry for the inconveniences.

**Comment by stephane-r** [comment] 2014-09-03 14:15
Thank you very much for your help! I removed / installed coffee script, I better :)

Live only works if I select my code should work without selection?

If I select my code, I get this (CTRL+SHIFT+ALT+ENTER) :

![coffee-live-true](https://cloud.githubusercontent.com/assets/4712791/4135217/2286d38c-3374-11e4-976e-c83b1a0e8ab2.jpg)

If I selected any code (CTRL+SHIFT+ALT+ENTER) :

![coffee-live-false](https://cloud.githubusercontent.com/assets/4712791/4135222/30b7dadc-3374-11e4-9d1c-9442dc134086.jpg)

An error on my part ?

Thank again

**Comment by philippotto** [comment] 2014-09-03 17:54
So, reinstallation of CoffeeScript helped? Great!

I just tested the Live Session command with an empty selection and noticed a small bug, which caused the live session to automatically end. I just fixed this (version 1.2.2 is the newest).

But actually, the bug doesn't explain why your output was "undefined". This should only happen if the cursor is in an empty line. Nevertheless, maybe the update helps. If not, we will try to find another way ;)

**Comment by stephane-r** [comment] 2014-09-04 06:48
Hi philippotto !

I think all is ok :) Full live code : 

![sans-titre-1](https://cloud.githubusercontent.com/assets/4712791/4145768/5992cbe8-33ff-11e4-9772-7ce7ddb53c71.jpg)
![sans-titre-2](https://cloud.githubusercontent.com/assets/4712791/4145767/59889d12-33ff-11e4-8c63-6b697372b8db.jpg)

Thank you very much for your help ! Fixed :)

**Edit last return** : if i test on file exist (not new file), live don't work (undefined). Yet, i've good message on cosole :

posting data for CoffeeScript
{'success': ['great success! [50|144167032198]']}

**Comment by philippotto** [comment] 2014-09-08 14:28
I'm not sure if I understand correctly: The live session mode didn't work on an existent file? What was the file content? What does the console output mean? It doesn't seem to originate from the EvalPrinter code base.

Please give more details about so concrete scenario so that I can reproduce the issue.

Please keep in mind, that the CoffeeScript code should be syntactically correct. Unfortunately, there is no real feedback at the moment. Instead, "undefined" will be printed. So, maybe incorrect syntax was the reason for your issue.

**Comment by philippotto** [comment] 2014-09-29 13:22
@LeG3nDz What's the status here? Is this still an issue? If so, please answer my questions from above. Otherwise, I would close the issue ;)

**Comment by stephane-r** [comment] 2014-09-30 19:15
Hi !

Problem fixed :)

**Comment by philippotto** [comment] 2014-09-30 21:47
Great!

**Closed as completed by philippotto** 2014-09-30 21:47 UTC
Labels: bug
